// @ts-check
// ObsidiaNote → Docusaurus 并行试点
// 内容通过两个 plugin-content-docs 实例直接指向 vault 的 Tech/、Assets/（外部 path），
// vault 只读、零拷贝。URL 形态与 Docsify 一致：/Tech/...、/Assets/...
import path from 'node:path';
import { themes as prismThemes } from 'prism-react-renderer';

const VAULT = '/root/webhost/vault';

// 分区落地页插件：把 /Tech、/Assets 注入为 exact 叶子路由（优先于 docs 根路由，
// 后者 exact:false 只兜底文档子路径）。卡片数据在 contentLoaded 阶段从 docs
// 插件的全量内容（loadedVersions）算好，序列化进路由 props——因此落地页是
// 普通叶子路由，会被 SSG 成 build/Tech/index.html 等静态文件：
//   直链 /Tech 由 nginx 直接伺服静态页，无需应用壳，也没有空壳 hydration
//   mismatch（React #418）。docs 根路由的组件拿不到 props.version（它只传给
//   version 路由自身），这是此前 DocsRoot 里 cards 为空的根因。
// path 必须与 docs 插件的 routeBasePath 一致（Tech/Assets，首字母大写）；
// 不能用 pluginId（tech/assets，小写），否则落地页落在 /tech 而非 /Tech。
const LANDING_SECTIONS = {
  tech: { path: '/Tech', label: 'Tech', subtitle: '技术运维 · 服务器 · 网络 · 工具软件' },
  assets: { path: '/Assets', label: 'Assets', subtitle: 'AI 资产 · 智能体 · 技能库 · 流水线' },
};

// 把 sidebars 里的顶层分类/文档转成卡片：title/subtitle/to。
// loadedVersion.sidebars 已是展开后的树（autogenerated 已解析成
// category/link 项），link 项带 id，需用 docsById 解析成 permalink。
function buildLandingCards(pluginId, loadedVersion) {
  if (!loadedVersion) return [];
  const docsById = new Map((loadedVersion.docs ?? []).map((d) => [d.id, d]));
  function normalizeItem(item) {
    if (item.type === 'link') {
      return {
        ...item,
        href: item.href ?? docsById.get(item.id)?.permalink ?? null,
      };
    }
    if (item.type === 'doc') {
      const doc = docsById.get(item.id);
      return {
        type: 'link',
        label: doc?.title ?? item.id,
        href: doc?.permalink ?? null,
        docId: item.id,
      };
    }
    if (item.type === 'category') {
      return { ...item, items: (item.items ?? []).map(normalizeItem) };
    }
    return item;
  }
  function firstLink(item) {
    if (item.type === 'link') return item.href;
    if (item.type === 'category') {
      for (const it of item.items ?? []) {
        const href = firstLink(it);
        if (href) return href;
      }
    }
    return null;
  }
  function countDocs(item) {
    if (item.type === 'link') return 1;
    if (item.type === 'category') {
      return (item.items ?? []).reduce((n, it) => n + countDocs(it), 0);
    }
    return 0;
  }
  const sidebar = (loadedVersion.sidebars?.[pluginId] ?? []).map(normalizeItem);
  const cards = [];
  for (const item of sidebar) {
    const to = firstLink(item);
    if (!to) continue;
    if (item.type === 'category') {
      cards.push({ title: item.label, subtitle: `${countDocs(item)} 篇`, to });
    } else if (item.type === 'link') {
      cards.push({ title: item.label, subtitle: '', to });
    }
  }
  return cards;
}

function landingPlugin() {
  return {
    name: 'landing',
    // 用 allContentLoaded：它收到聚合的 allContent（含各 docs 插件的
    // loadedVersions）。contentLoaded 只拿得到本插件自己的 content。
    async allContentLoaded({ allContent, actions }) {
      const { addRoute } = actions;
      for (const [pluginId, section] of Object.entries(LANDING_SECTIONS)) {
        const content = allContent['docusaurus-plugin-content-docs']?.[pluginId];
        const loadedVersion = content?.loadedVersions?.[0];
        const cards = buildLandingCards(pluginId, loadedVersion);
        console.log(
          `[landing] ${pluginId}: ${cards.length} cards (loadedVersion: ${Boolean(loadedVersion)})`,
        );
        addRoute({
          path: section.path,
          exact: true,
          component: '@site/src/components/LandingPage',
          props: { cards, section },
        });
      }
    },
  };
}

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'ObsidiaNote',
  tagline: '技术运维笔记与 AI 资产',
  favicon: 'img/favicon.svg',

  url: 'http://localhost',
  baseUrl: '/',
  organizationName: 'HerrDanke',
  projectName: 'ObsidiaNote',

  // 评估期宽容：个别文件（HTML 裸标签等）不打断构建，仅告警
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  onDuplicateRoutes: 'warn',

  i18n: {
    defaultLocale: 'zh-Hans',
    locales: ['zh-Hans'],
  },

  // 全局用纯 markdown 渲染（非 MDX）：vault 笔记含裸 HTML 标签，MDX 会当 JSX 报错。
  // format:'md' 时 mdx-loader 启用 rehypeRaw，裸 HTML 直接渲染；
  // admonitions/代码高亮/TOC 均为 remark 级，不受影响。
  markdown: {
    format: 'md',
  },

  themes: [
    // 本地中文分词全文搜索（jieba）
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        language: ['en', 'zh'],
        searchResultLimits: 10,
        searchResultContextMaxLength: 60,
        // 本站没有 id 为 default 的 docs 实例（只有 tech/assets 两个），
        // 非文档页（主页等）上 activePlugin 为空时用它兜底，避免报错
        docsPluginIdForPreferredVersion: 'tech',
        // 插件默认只索引 /docs 路由；本站文档在 /Tech/ 和 /Assets/，必须显式声明
        docsRouteBasePath: ['Tech', 'Assets'],
        docsDir: [path.resolve(VAULT, 'Tech'), path.resolve(VAULT, 'Assets')],
        indexBlog: false,
      },
    ],
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: false,
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  plugins: [
    landingPlugin,
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'tech',
        path: path.resolve(VAULT, 'Tech'),
        routeBasePath: 'Tech',
        sidebarPath: './sidebars-tech.js',
        // 纯 markdown 渲染（非 MDX）：vault 笔记含裸 HTML 标签，MDX 会当 JSX 报错；
        // admonitions/代码高亮/TOC 都是 remark 级，不受影响
        // 与 Docsify 的 gen-sidebar 语义对齐：URL 用文件名（去扩展名），不注入前缀
        showLastUpdateTime: false,
        showLastUpdateAuthor: false,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'starred',
        path: path.resolve(VAULT, 'starred'),
        routeBasePath: 'starred',
        sidebarPath: './sidebars-starred.js',
        showLastUpdateTime: false,
        showLastUpdateAuthor: false,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'assets',
        path: path.resolve(VAULT, 'Assets'),
        routeBasePath: 'Assets',
        sidebarPath: './sidebars-assets.js',
        // catalog/ 是 ai-assets 展示站（8083）的内容源，不在本知识库站展示。
        // exclude 后文档页、落地页卡片、搜索索引一并排除
        exclude: ['catalog/**'],
        showLastUpdateTime: false,
        showLastUpdateAuthor: false,
      },
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {
        defaultMode: 'light',
        respectPrefersColorScheme: true,
      },
      navbar: {
        title: 'ObsidiaNote',
        logo: {
          alt: 'ObsidiaNote',
          src: 'img/logo.svg',
          srcDark: 'img/logo-dark.svg',
        },
        items: [
          { to: '/starred/starred-repos', label: '⭐ 标星', position: 'left' },
          { type: 'docSidebar', sidebarId: 'tech', label: 'Tech', position: 'left', docsPluginId: 'tech' },
          { type: 'docSidebar', sidebarId: 'assets', label: 'Assets', position: 'left', docsPluginId: 'assets' },
        ],
      },
      footer: {
        style: 'light',
        copyright: `ObsidiaNote · 个人知识库`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
    }),
};

export default config;
